package net.deskplate.mybatis.entity;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.id
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.name
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Employee.role
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.id
     *
     * @return the value of Employee.id
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.id
     *
     * @param id the value for Employee.id
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.name
     *
     * @return the value of Employee.name
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.name
     *
     * @param name the value for Employee.name
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Employee.role
     *
     * @return the value of Employee.role
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Employee.role
     *
     * @param role the value for Employee.role
     *
     * @mbggenerated Sat Jul 02 18:07:10 JST 2022
     */
    public void setRole(String role) {
        this.role = role;
    }
}