package net.deskplate.mybatis.entity;

import java.util.List;
import net.deskplate.mybatis.entity.Employee;
import net.deskplate.mybatis.entity.EmployeeExample;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Employee
     *
     * @mbggenerated Sun Jul 03 16:15:13 JST 2022
     */
    int updateByPrimaryKey(Employee record);
}